questions = [
    "Would you rather fridge cold chocolate or room temperature chocolate?",
    "At night do you worry more about someone breaking in or a kitchen fire?",
    "Do you sometimes think there are snakes in the toilet bowl?",
    "Would you rather drink toilet water or your own wee?",
    "Do you prefer your ice cream all melty or all hard?",
    "Burps or farts?",
    "Would you push a baby out of your vagina?",
    "What's the best bit of the butt?",
    "What's your favourite ice?",
    "Were you really tall as a child? What did your mum do about clothes?",
    "When you have picky bits for dinner, what are your favourite picky bits?",
    "What's the silliest argument you've had with someone?",
    "What’s your perfect meal from Harvester?",
    "Do you need warm milk (with chocolate) for sleepy times?",
    "What are your favourite pancake toppings?",
    "Where would be the worst place to have an itchy rash (that’s not gross or serious, just really itchy) that isn’t your genitals?",
    "If you could go to any time/period in history and just observe, see all the best and worst bits but not interact/change the course of history what time would you go to?",
    "What would you be the god of?",
    "Do you believe in witchcraft?",
    "If you had invisibility would you use it to just look at boobs and penises?",
    "Do you still eat the same cereal you did as a kid?",
    "When you were a kid, did you add sugar to every cereal you ate? If so, which sugar?",
    "What are the cutest puppies?",
    "Please can you tell me your best and favourite vegetarian dinner recipes?",
    "If you are in the Good Place, does the awkwardness of threesomes not happen?",
    "When you were poor/didn't have any money, what was your cheap meal? Would you still eat it now?",
    "Just... why men?",
    "Why does Trent Reznor dislike Marilyn Manson please?",
    "Am I in Harry Potter?!",
    "How does it feel to be grown up?",
    "Are you going to bake today?",
    "Who owns the goat?",
    "Would you eat a giant egg to yourself?",
    "What’s your best type of Easter egg? Do you like a big ole Cadbury’s one, or something fancier?",
    "When you have tuna pasta bake, do you make two?",
    "What’s the best pastry you’ve made?",
    "Is there a decent fake chicken Kiev?",
    "Who needs a 5kg turkey?!",
    "Should we all go to the cinema to see Thor?",
]
