questions = [
    "Would you rather fridge cold chocolate or room temperature chocolate?",
    "At night do you worry more about someone breaking in or a kitchen fire?",
    "Do you sometimes think there are snakes in the toilet bowl?",
    "Would you rather drink toilet water or your own wee?",
    "Do you prefer your ice cream all melty or all hard?",
    "Burps or farts?",
    "Would you push a baby out of your vagina?",
    "What's the best bit of the butt?",
    "What's your favourite ice?",
    "Were you really tall as a child? What did your mum do about clothes?",
    "When you have picky bits for dinner, what are your favourite picky bits?",
    "What's the silliest argument you've had with someone?",
    "What’s your perfect meal from Harvester?",
    "Do you need warm milk (with chocolate) for sleepy times?",
]
